components/person.vue, nuxt.config.js, package.json, plugins/fa.js
Social icons added to buttons on person component
=> Social Icons

components/MenteeCard.vue, components/MentorCard.vue, components/Navbar.vue
- Fix missing image issue
- Change logo font style
- Refactor mobile view
- Filter social media icon
- Redirect avatar to profile page
=> Fix minor issues

components/Card.vue
https://github.com/cagataycali/find-mentor/issues/29
target blank for social links on profile cards and added a element titles for seo
=> :lipstick: target blank for social links on profile cards

components/Navbar.vue, components/person.vue, pages/index.vue
-layout text color changed to white
=> -background color animation effect added

components/Navbar.vue, components/person.vue, pages/index.vue
Reverts cagataycali/find-mentor#27
=> Revert "-background color animation effect added"

components/person.vue
Twitter timeline embedded on person component
=> Embed Twitter Timeline

pages/mentee/_slug.vue, pages/mentor/_slug.vue
Mentor ve Mentee detay sayfalarına temel meta etiketleri eklenmiştir.
Avatarlar base'de size 200 alındığı için open graph görsellerinde de o boyutta görüntülenecektir. Bunların ilerleyen bir süreçte spesifik değerler atanabilir hale getirilmesini tavsiye edebilirim.
=> :mag: Added basic meta tags to person pages

README.md, components/person.vue
- Redesign profile page
- Update readme.md
=> Update profile page design

components/person.vue
- Add lazy loading params for avatar
=> Add lazy loading params for avatar

components/Card.vue
#31 Geliştirmesi başka bir geliştirme sebebiyle uçmuş. Reviewlerde aman dikkat :))
Profile kartlardaki sosyal bağlantılar artık yeni sekmede açılıyor ve seo'ya yönelik katkı için title attr. eklendi.
=> :lipstick: target blank and seo title for social links on cards

Mentees.md
Yanlislar olursa birlikte duzeltelim.
=> Created Mentees.md

Mentors.md
Yanlislar olursa birlikte duzeltelim. (2)
=> Created Mentors.md Guide

components/Navbar.vue, docs/index.html
Fixed the grammatical error in the navbar.
=> Updated "how it works" in navbar.

components/Card.vue, components/person.vue, generate.js
- Refactor avatar structure
- Refactor generateAvatar function
=> Refactor avatar

components/Navbar.vue
Reverts cagataycali/find-mentor#75
=> Revert "Navbar  responsive düzeltmesi "

content/activeMentorships.json, content/persons.json, generate.js, pages/mentorships.vue, static/activeMentorships.json, static/persons.json
First messed with the @cagataycali, this disrespectful error shall be gone.
=> fixed /mentorships page

pages/guide.vue
=> fixed contributor avatar links

generate.js, pages/guide.vue
now we check if the contributor is in the google sheet and use
their findnetwork.com profile for avatar links if it does
=> avatar links, changelog:

components/ActiveMentorshipCard.vue
Now activementroshipcard able to work with darkmode
=> Update activementoshipcard for darkmode

components/person.vue
Link düzeltme ve  linke attribute ekleme
=> mentore proje link düzeltmesi  ve blank target

components/header/AppHeader.vue
this is not very performant, cuz i don't know bootstrap.
did my best tho.
@cagataycali acil PR bu en yakin vakit bakiver.
test ettim kendi telefonumda (ve browser'da) OK
=> fixed searchbar issue on mobile

components/card/PersonCard.vue
Added some bootstrap and positioning queries. After the bootstrap stuff a spacing problem occured I tried to solve it with margin. We can check it together.
=> Updated PersonCard.vue 🧨

components/card/PersonCard.vue, components/card/ProfilePersonCard.vue, mixins/getCapitalPersonName.js, mixins/index.js
=> Feature/129 :lipstick: Capital Case Person Name

pages/guide.vue
In light mode I think users hardly recognize cards so I added some box-shadow for handle this situation.
=> Updated guide.vue 💣

components/button/PersonNavigationButton.vue, components/detail/person/PersonDetail.vue, mixins/getCapitalPersonName.js, mixins/getPersonTypeClass.js, mixins/getPersonTypeColor.js, mixins/getPersonTypeLabel.js, package.json, pages/index.vue, pages/peer/_slug.vue, plugins/fa.js, yarn.lock
#133 
1200px yukarda solda ve sağda peer navigation butonlar görünür. Mobil için farklı bir pr üzerinde ele alınabilir. Ek olarak asyncData > fetch yapılması gerekti bu değişim sebebi ile head modellerinde model varlığı kontrol edilmek zorunda. Kod iyileştirmesi işin kapsamına göre farklı bir pr üzerinde ele alınabilir.
=> Feature/133 :lips: Peer navigation feature on person page

components/card/PersonCard.vue
Reverts cagataycali/find-mentor#137
=> Revert "Updated PersonCard.vue 🧨"

components/card/ProfilePersonCard.vue, pages/mentees.vue, pages/mentors.vue
=> Fix : Blinking no result. Add: Share at twitter

components/card/ProfilePersonCard.vue
Fix: Share at twitter button mobile-friendly
=> Fix: Share at twitter button mobile-friendly

components/detail/person/PersonDetail.vue
- Add avatar and update design in contributed project section
- Add avatar to the active mentorships section
=> Update 'Active Mentorships' and 'Contributed' sections

components/detail/person/PersonDetail.vue
=>  The twitter embed does not have the same height the feedback section #117

components/detail/person/PersonDetail.vue, content/activeMentorships.json, content/persons.json, generate.js, getContributons.js, pages/index.vue, static/activeMentorships.json, static/persons.json, test.js
https://github.com/cagataycali/find-mentor/issues/159
=> Fixed: Missing column #159

components/detail/person/PersonDetail.vue
=> Fix twitter size issue

components/card/ProfilePersonCard.vue, components/detail/person/PersonDetail.vue, plugins/fa.js
Refactored return statement. Also I added "check out active mentorships" button which scrolls to Active Mentorships h tag.
=> 🔨 Check active mentorships button and refactor

components/card/PersonCard.vue, components/card/ProfilePersonCard.vue
Hey @cagataycali, great job 👏. I appreciate your hard work!
This PR creates a hovering effects on social media icons ✨.
=> Add hover effects on related social media icons

content/mentees.md
Another sentence can be "There is another approach .."
=> Fix grammar in the sentence: "There is exists.."

content/mentees.md, content/mentors.md
Here is another suggested improvement:
-Instead of "project for contribution", "project to contribute" can be used.
=> Fix spelling errors

assets/style/scss/shared/_nuxt-layout.scss
=> Feature/176 :lipstick: Style fix for router-view-wrapper

assets/style/css/variables/color.css, assets/style/scss/base/_general.scss, assets/style/scss/plugins/_browserhack.scss, components/preloader/AppPreloader.vue, layouts/default.vue, store/appPreloader/actions.js, store/appPreloader/getters.js, store/appPreloader/mutations.js, store/appPreloader/state.js
Uygulama (Web sitesi) yüklenirken bir fullscreen bir preloader element görünür. Sadece ilk açtığınızda karşılar, her rota gezmesinde çalışmaz. Bu yaklaşımla sayfa ilk yüklenirken oluşan css flash'ın önüne geçildi.
=> :lips: CSS flash bypass with App Preloader element.

generate.js
I couldn't test this code because google blocked me for doing (accidentally) too many requests. This should theoretically work tho so @selimdoyranli can you test this please?
=> made writing content asynchronous

assets/style/css/variables/color.css, components/card/PersonCard.vue, components/card/ProfilePersonCard.vue, components/header/AppHeader.vue
I added dark-mode colors to github icons in ProfileCard, Header and User Profile
=> dark-mode github-icon colors added

generate.js
Regex can be tested over: https://regex101.com/r/kgPV7p/1
=> Replace regexp for www cases

assets/style/css/variables/color.css, components/header/AppHeader.vue, pages/events.vue, pages/index.vue
=> Add events pages

firebase.html
Experimental.
We'll use the basic idea for the next milestone of the app.
=> Add firebase auth & firestore example

components/footer/AppFooter.vue, layouts/default.vue
=> added to public link footer

pages/jobs.vue
I am not sure about ```v-for``` usage. 
[Issue](https://github.com/cagataycali/find-mentor/issues/224)
=> Basic jumbotron added

pages/jobs.vue
=> Update jobs pages design 

components/badge/AppBadge.vue, components/button/PersonNavigationButton.vue, components/card/ProfilePersonCard.vue
=> hire me button style changed, mail to link added.

components/card/ActiveMentorshipCard.vue, components/footer/AppFooter.vue, layouts/default.vue, pages/guide.vue, pages/index.vue, pages/mentorships.vue
- Update mentorships page design
- Move AppFooter to default.vue
=> Update mentorships page design

assets/style/css/variables/color.css, components/card/ProfilePersonCard.vue, plugins/fa.js
https://github.com/cagataycali/find-mentor/issues/248
=> #248 Stackoverflow Link added

components/card/JobCard.vue
#245 
Logo'ya beyaz background eklendi.
=> #245 :lipstick: UI improvements for JobCard

nuxt.config.js, pages/peer/_slug.vue
solve: Mentors and mentees page main content is flickering when user skip to the next user.
=> solve :  content is flickering and it seems ugly

generate.js
Added trim method to post object, so any unnecessary space that exists will be deleted.
=> Remove space on Mentorships detail

pages/index.vue
Click here for all mentors and Click here for all mentees were changed to look fancy a bit more
=> Buttons' lookings were changed
